//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloopMasterBG
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostPriceHistory
    {
        public int ArticleProduct { get; set; }
        public int Cost { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
