//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloopMasterBG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FloopMasterEntities : DbContext
    {

        public static FloopMasterEntities _context;

        public static FloopMasterEntities GetContext()
        {
            if (_context == null)
                _context = new FloopMasterEntities();
            return _context;
        }
        public FloopMasterEntities()
            : base("name=FloopMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationProductParthers> ApplicationProductParthers { get; set; }
        public virtual DbSet<ManyArticle> ManyArticle { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Material_Product> Material_Product { get; set; }
        public virtual DbSet<MaterialProviderHistory> MaterialProviderHistory { get; set; }
        public virtual DbSet<Pathers> Pathers { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SalePlace> SalePlace { get; set; }
        public virtual DbSet<SalePlacePathers> SalePlacePathers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<TypePathers> TypePathers { get; set; }
        public virtual DbSet<TypeProduct> TypeProduct { get; set; }
        public virtual DbSet<TypeProvider> TypeProvider { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<CostPriceHistory> CostPriceHistory { get; set; }
        public virtual DbSet<MaterialHistory> MaterialHistory { get; set; }
        public virtual DbSet<MinCostHistory> MinCostHistory { get; set; }
        public virtual DbSet<ProductHistory> ProductHistory { get; set; }
    }
}
