//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloopMasterBG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Material_Product = new HashSet<Material_Product>();
            this.MaterialHistory = new HashSet<MaterialHistory>();
            this.MaterialProviderHistory = new HashSet<MaterialProviderHistory>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string NameMaterial { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public int UnitPackage { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public decimal Cost { get; set; }
        public int QuantityInStock { get; set; }
        public Nullable<int> MinimalQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Product> Material_Product { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialHistory> MaterialHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProviderHistory> MaterialProviderHistory { get; set; }
    }
}
