//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloopMasterBG
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialProviderHistory
    {
        public int ID { get; set; }
        public int ProviderID { get; set; }
        public int MaterialID { get; set; }
        public int WorkerID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public decimal Cost { get; set; }
        public int Count { get; set; }
        public System.DateTime DateDelivery { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
