//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloopMasterBG
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePlacePathers
    {
        public int IDSalePlace { get; set; }
        public int IDPathers { get; set; }
        public int ID { get; set; }
    
        public virtual Pathers Pathers { get; set; }
        public virtual SalePlace SalePlace { get; set; }
    }
}
